insert into countries_ctg values
('MX','Mexico'),
('US', 'Estados Unidos');

INSERT INTO states_ctg VALUES
('AS','MX','Aguascalientes'),
('BC','MX','Baja California'),
('BS','MX','Baja California Sur'),
('CC','MX','Campeche'),
('CS','MX','Chiapas'),
('CH','MX','Chihuahua'),
('CL','MX','Coahuila'),
('CM','MX','Colima'),
('DF','MX','Ciudad de México'),
('DG','MX','Durango'),
('GT','MX','Guanajuato'),
('GR','MX','Guerrero'),
('HG','MX','Hidalgo'),
('JC','MX','Jalisco'),
('MC','MX','México'),
('MN','MX','Michoacán'),
('MS','MX','Morelos'),
('NT','MX','Nayarit'),
('NL','MX','Nuevo León'),
('OC','MX','Oaxaca'),
('PL','MX','Puebla'),
('QT','MX','Querétaro'),
('QR','MX','Quintana Roo'),
('SP','MX','San Luis Potosí'),
('SL','MX','Sinaloa'),
('SR','MX','Sonora'),
('TC','MX','Tabasco'),
('TS','MX','Tamaulipas'),
('TL','MX','Tlaxcala'),
('VZ','MX','Veracruz'),
('YN','MX','Yucatán'),
('ZS','MX','Zacatecas');

insert into ciudades (nombre, estado) values
('Aguascalientes','AS'),
('Asientos','AS'),
('Calvillo','AS'),
('Mexicali','BC'),
('Tecate','BC'),
('Tijuana','BC'),
('Comondú','BS'),
('La Paz','BS'),
('Loreto','BS'),
('Calakmul','CC'),
('Calkiní','CC'),
('Campeche','CC'),
('Acacoyagua','CS'),
('Acala','CS'),
('Acapetahua','CS'),
('Ahumada','CH'),
('Aldama','CH'),
('Allende','CH'),
('Abasolo','CL'),
('Acuña','CL'),
('Allende','CL'),
('Armería','CM'),
('Colima','CM'),
('Comala','CM'),
('Álvaro Obregón','DF'),
('Azcapotzalco','DF'),
('Benito Juárez','DF'),
('Canatlán','DG'),
('Canelas','DG'),
('Coneto de Comonfort','DG'),
('Abasolo','GT'),
('Acámbaro','GT'),
('Apaseo el Alto','GT'),
('Acapulco de Juárez','GR'),
('Acatepec','GR'),
('Ahuacuotzingo','GR'),
('Acatlán','HG'),
('Acaxochitlán','HG'),
('Actopan','HG'),
('Acatic','JC'),
('Acatlán de Juárez','JC'),
('Amacueca','JC'),
('Acambay','MC'),
('Acolman','MC'),
('Aculco','MC'),
('Acuitzio','MN'),
('Aguililla','MN'),
('Álvaro Obregón','MN'),
('Amacuzac','MS'),
('Atlatlahucan','MS'),
('Axochiapan','MS'),
('Acaponeta','NT'),
('Ahuacatlán','NT'),
('Amatlán de Cañas','NT'),
('Abasolo','NL'),
('Agualeguas','NL'),
('Allende','NL'),
('Abejones','OC'),
('Ánimas Trujano','OC'),
('Chahuites','OC'),
('Acajete','PL'),
('Acateno','PL'),
('Acatlán','PL'),
('Amealco de Bonfil','QT'),
('Arroyo Seco','QT'),
('Colón','QT'),
('Benito Juárez','QR'),
('Cozumel','QR'),
('Felipe Carrillo Puerto','QR'),
('Ahualulco','SP'),
('Alaquines','SP'),
('Aquismón','SP'),
('Ahome','SL'),
('Angostura','SL'),
('Badiraguato','SL'),
('Aconchi','SR'),
('Agua Prieta','SR'),
('Alamos','SR'),
('Balancán','TC'),
('Cárdenas','TC'),
('Centla','TC'),
('Abasolo','TS'),
('Aldama','TS'),
('Altamira','TS'),
('Altzayanca','TL'),
('Apizaco','TL'),
('Calpulalpan','TL'),
('Acajete','VZ'),
('Alvarado','VZ'),
('Amatitlán','VZ'),
('Abalá','YN'),
('Cuzamá','YN'),
('Dzán','YN'),
('Apulco','ZS'),
('Apozol','ZS'),
('Calera','ZS');

insert into universities_ctg(city, name, latitude, longitude) VALUES
(6, 'Universidad Tecnológica de Tijuana', 32.4602500, -116.8255840);

insert into universities_ctg(city, name, latitude, longitude) VALUES
(6, 'Instituto Tecnológico de Tijuana', 32.535222, -116.926070);

insert into universities_ctg(city, name, latitude, longitude) VALUES
(5, 'UABC Facultad de Ingeniería y Negocios Tecate', 32.568249, -116.626413);

insert into brands_ctg(name) VALUES
('Ford'),
('Nissan'),
('Chevrolet'),
('Toyota'),
('Wolkswagen'),
('Honda'),
('BMW'),
('AUDI'),
('SEAT'),
('Hyundai'),
('Mazda');


insert into models_ctg (brand, name) VALUES
(1, 'Sedan'),
(1, 'Mustang'),
(1, 'Windstar'),
(1, 'Ranger'),
(1, 'Fusion'),
(1, 'Ikon'),
(1, 'Orion'),
(1, 'Probe'),
(1, 'Aerostar'),
(1, 'Sierra'),
(1, 'Fiesta'),
(1, 'Focus'),
(1, 'F150'),
(1, 'Lobo'),
(1, 'Courier'),
(2, 'Qashqai'),
(2, 'Wagon'),
(2, 'Evalia'),
(2, 'Rogue'),
(2, 'Terrano'),
(2, 'Tiida'),
(2, 'Tsuru'),
(2, 'Altima'),
(2, 'Sentra'),
(2, 'Skiline'),
(2, 'Frontier'),
(2, 'Hikari'),
(2, 'Z350'),
(2, 'X Trail'),
(2, 'Cube'),
(2, 'Versa'),
(2, 'Murano'),
(2, 'Maxima'),
(3, 'Equinox'),
(3, 'Rodeo'),
(3, 'Tahoe'),
(3, 'Uplander'),
(3, 'Impala'),
(3, 'Onix'),
(3, 'Optra'),
(3, 'Prisma'),
(3, 'Aveo'),
(3, 'Agile'),
(3, 'Astra'),
(3, 'Sail'),
(3, 'S10'),
(3, 'Spark'),
(3, 'GT'),
(3, 'Kalos'),
(3, 'Lumina'),
(3, 'Camira'),
(3, 'Beat'),
(3, 'Blaze'),
(4, 'Thundra'),
(4, 'Tacoma'),
(4, 'Prius'),
(4, 'Supra'),
(4, 'Sienna'),
(4, 'Corolla'),
(4, 'Thundra'),
(5, 'R32'),
(5, 'Golf'),
(5, 'Jetta'),
(5, 'Kombi'),
(5, 'Vento'),
(5, 'Beetle'),
(6, 'Accord'),
(6, 'Civic'),
(6, 'Element'),
(6, 'Integra'),
(6, 'Del Sol'),
(7, 'E46'),
(7, 'Ursulet'),
(7, 'Alpina'),
(7, 'D3'),
(7, 'Coupe'),
(7, 'M3'),
(8, 'TT'),
(8, 'A3'),
(8, 'Z4'),
(8, 'TT'),
(8, 'TT'),
(9, 'Ibiza'),
(9, 'Ateca'),
(10, 'Tucson'),
(10, 'Tiburon'),
(10, 'Optima'),
(10, 'Accent'),
(10, 'Sonata'),
(11, 'RX8'),
(11, 'Allegro');

INSERT INTO profiles_ctg VALUES 
('D','Driver'),
('P','Passenger');



