INSERT INTO states_ctg(code, name) VALUES
('AS','Aguascalientes'),
('BC','Baja California'),
('BS','Baja California Sur'),
('CC','Campeche'),
('CS','Chiapas'),
('CH','Chihuahua'),
('CL','Coahuila'),
('CM','Colima'),
('DF','Ciudad de México'),
('DG','Durango'),
('GT','Guanajuato'),
('GR','Guerrero'),
('HG','Hidalgo'),
('JC','Jalisco'),
('MC','México'),
('MN','Michoacán'),
('MS','Morelos'),
('NT','Nayarit'),
('NL','Nuevo León'),
('OC','Oaxaca'),
('PL','Puebla'),
('QT','Querétaro'),
('QR','Quintana Roo'),
('SP','San Luis Potosí'),
('SL','Sinaloa'),
('SR','Sonora'),
('TC','Tabasco'),
('TS','Tamaulipas'),
('TL','Tlaxcala'),
('VZ','Veracruz'),
('YN','Yucatán'),
('ZS','Zacatecas');